on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myfirstazuredockerregistry.azurecr.io
        username: ${{ secrets.acr_myfirstazuredockerregistry_username }}
        password: ${{ secrets.acr_myfirstazuredockerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myfirstazuredockerregistry.azurecr.io/myfirstkubcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myfirstazuredockerregistry.azurecr.io/myfirstkubcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myfirstkubcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep my-first-kub-cluster86de | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace my-first-kub-cluster86de`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: my-first-kub-cluster86de
        container-registry-url: myfirstazuredockerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_myfirstazuredockerregistry_username }}
        container-registry-password: ${{ secrets.acr_myfirstazuredockerregistry_password }}
        secret-name: myfirstkubcldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: my-first-kub-cluster86de
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myfirstazuredockerregistry.azurecr.io/myfirstkubcluster:${{ github.sha }}
        imagepullsecrets: |
          myfirstkubcldockerauth
